#ifndef _BIT_MATH_H_
#define _BIT_MATH_H_



#define SET_BIT(VAR,BIT_NO) (VAR|=(1<<BIT_NO))
#define CLR_BIT(VAR,BIT_NO) (VAR&=(~(1<<BIT_NO)))
#define TOG_BIT(VAR,BIT_NO) (VAR^=(1<<BIT_NO))
#define GET_BIT(VAR,BIT_NO) ((VAR>>BIT_NO)&0x01)
#define MAP(VALUE,RANGE1_UPPER,RANGE1_LOWER,RANGE2_UPPER,RANGE2_LOWER)  VALUE=((VALUE*(RANGE1_UPPER-RANGE1_LOWER))/(RANGE2_UPPER-RANGE2_LOWER))
#endif
